### ISSUE TITLE
Package Warning install ChefDK on Ubuntu 14.04

### ISSUE THREAD

**Issue by johnmccrae** [chef/omnibus-chef#195]
I am installing the ChefDK on a brand-new Active Directory joined installation of Ubuntu 14.04 server. The download goes correctly but when I double-click the deb package to bring up the software center, I get a warning that says:

"This Package is of Bad Quality"

When i click on the details I get the following data:

"Lintian check results for /home/<path goes here>/chefdk_0.1.0-1_amd64.deb
E: chefdk: maintainer-address-missing Opscode, Inc"

So maybe there are 2 bugs here. The first being the warning about the package. The second being that it references a company that does not exist - Opscode.

![upload 1](https://cloud.githubusercontent.com/assets/4855887/3587764/64dda2ce-0c3c-11e4-8ad1-cb18cdd8199a.png)

**Comment by kowal** [comment]
I have a same question as @TG9541 - is Ubuntu 14.04 actually supported?

**Comment by charlesjohnson** [comment]
According to RFC021 (Platform Support Policy), Ubuntu 14.04 is a tier 1 supported platform for ChefDK.

https://github.com/opscode/chef-rfc/blob/master/rfc021-platform-support-policy.md

**Comment by tyler-ball** [comment]
I added an issue to add build and testing support for Ubuntu 14.04 - https://github.com/chef/omnibus-chef/issues/339

When this gets added, the download page should automatically be updated to reflect the new packages.

**Comment by stucki** [comment]
Any news here? What version should I now install on Ubuntu 14.04?

**Comment by charlesjohnson** [comment]
The page at downloads.chef.io currently shows support for Ubuntu 14.04 for both the Chef-client and ChefDK packages.

Do we have resolution on the "bad quality" issues above?

**Comment by stucki** [comment]
Here is still only 12.04 and 13.10 mentioned: https://downloads.chef.io/chef-dk/ubuntu/

**Comment by charlesjohnson** [comment]
At https://downloads.chef.io/chef-dk/ubuntu/ I'm seeing ChefDK for Ubuntu 0.4., with support mentioned for Ubuntu 14.04. Maybe you need to cache clear on your browser?

![screen shot 2015-03-24 at 2 54 02 pm](https://cloud.githubusercontent.com/assets/541978/6813820/06b68eb6-d236-11e4-85c8-a58e32c505f5.png)

**Comment by stucki** [comment]
Oh! Indeed my cache was just outdated. Cleared the cache and now it looks good. Thank you!

**Comment by HeathNaylor** [comment]
Just so you know, this error persists to 0.4.0

```
Lintian check results for /home/user/Downloads/chefdk_0.4.0-1_amd64 (1).deb:
E: chefdk: maintainer-address-missing Chef Software, Inc.
```

**Comment by charlesjohnson** [comment]
ChefDK 0.4.0 shipped on February 2nd. Omnibus was updated to support [http://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-Maintainer](Debian 5.6.2 Maintainer spec) , and the [https://github.com/chef/omnibus-chef/commit/c5de7cc40a4aab07919ffb567d509435cfd5b221](maintainer fields in the project definitions were updated) about February 18th.

The next release should pass, but leaving this open until after it ships and we can verify.

**Comment by johnmccrae** [comment]
Lamont, I think this came to the wrong John?

**Comment by lamont-granquist** [comment]
nope, you opened this ticket originally, so you got the notice that i closed it when i cleaned up the tickets...

**Comment by johnmccrae** [comment]
Well, thanks then!
