### ISSUE TITLE
Building chef-client for s390x rhel-7 fails 

### ISSUE THREAD

**Issue by johusta** [chef/omnibus-chef#287]
Hi I am trying to build the latest chef-client for rhel7 s390x.
First error I get is that fakeroot is not found. After doing some research it appears that they pulled fakeroot out of the release as rpmbuild no longer requires it. 
 
I was able to work around it by installing a rhel 6 version of the fakeroot package.

Now I get the following error and don't know how to get around this one.
Also can I over ride the package name some how? They way I used to do that before using override in my chef.rb file does not seem to work.

                    [Packager::RPM] W | The `version' component of RPM package names can only include alphabetical characters (a-z, A-Z), numbers (0-9), dots (.), plus signs (+), and underscores (_). Converting `12.0.0-alpha.2+20141110232258.git.652.7bd20f0' to `12.0.0_alpha.2+20141110232258.git.652.7bd20f0'.
                       [Compressor] I | No compressor defined for `rhel'.

**Comment by cosmin-altiscale** [comment]
How did you solve the No compressor defined for rhel part? I'm running into it.

**Comment by danielhass** [comment]
I also tried to use the chef-client on a s390x system with SLES. I discovered a little workaround. Compile or install a supported ruby version and install chef from RubyGems.org (https://rubygems.org/gems/chef). Works for me.
