### ISSUE TITLE
HealthCheck fails because of "Unsafe Dependancy" on libgcc_s.so.1 and libstdc++.so.6 when building ChefDK on Arch Linux

### ISSUE THREAD

**Issue by Uncurlhalo** [chef/omnibus-chef#330]
While trying to build ChefDK on an Arch Linux machine I encounter the following error during the health check stage of the build.
```
                      [HealthCheck] E | Failed!
                      [HealthCheck] E | The following libraries have unsafe or unmet dependencies:
    --> /opt/chefdk/embedded/lib/ruby/gems/2.1.0/extensions/x86_64-linux/2.1.0/dep_selector-1.0.3/dep_gecode.so
    --> /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/dep_selector-1.0.3/ext/dep_gecode/dep_gecode.so
    --> /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/dep_selector-1.0.3/lib/dep_gecode.so

                      [HealthCheck] E | The following binaries have unsafe or unmet dependencies:

                      [HealthCheck] E | The following libraries cannot be guaranteed to be on target systems:
    --> /usr/lib/libstdc++.so.6 (0x00007f6df4fa0000)
    --> /usr/lib/libgcc_s.so.1 (0x00007f6df46e1000)
    --> /usr/lib/libstdc++.so.6 (0x00007f5ea2b7a000)
    --> /usr/lib/libgcc_s.so.1 (0x00007f5ea22bb000)
    --> /usr/lib/libstdc++.so.6 (0x00007f897cdc2000)
    --> /usr/lib/libgcc_s.so.1 (0x00007f897c503000)

                      [HealthCheck] E | The precise failures were:
    --> /opt/chefdk/embedded/lib/ruby/gems/2.1.0/extensions/x86_64-linux/2.1.0/dep_selector-1.0.3/dep_gecode.so
    DEPENDS ON: libstdc++.so.6
      COUNT: 1
      PROVIDED BY: /usr/lib/libstdc++.so.6 (0x00007f6df4fa0000)
      FAILED BECAUSE: Unsafe dependency
    --> /opt/chefdk/embedded/lib/ruby/gems/2.1.0/extensions/x86_64-linux/2.1.0/dep_selector-1.0.3/dep_gecode.so
    DEPENDS ON: libgcc_s.so.1
      COUNT: 1
      PROVIDED BY: /usr/lib/libgcc_s.so.1 (0x00007f6df46e1000)
      FAILED BECAUSE: Unsafe dependency
    --> /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/dep_selector-1.0.3/ext/dep_gecode/dep_gecode.so
    DEPENDS ON: libstdc++.so.6
      COUNT: 1
      PROVIDED BY: /usr/lib/libstdc++.so.6 (0x00007f5ea2b7a000)
      FAILED BECAUSE: Unsafe dependency
    --> /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/dep_selector-1.0.3/ext/dep_gecode/dep_gecode.so
    DEPENDS ON: libgcc_s.so.1
      COUNT: 1
      PROVIDED BY: /usr/lib/libgcc_s.so.1 (0x00007f5ea22bb000)
      FAILED BECAUSE: Unsafe dependency
    --> /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/dep_selector-1.0.3/lib/dep_gecode.so
    DEPENDS ON: libstdc++.so.6
      COUNT: 1
      PROVIDED BY: /usr/lib/libstdc++.so.6 (0x00007f897cdc2000)
      FAILED BECAUSE: Unsafe dependency
    --> /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/dep_selector-1.0.3/lib/dep_gecode.so
    DEPENDS ON: libgcc_s.so.1
      COUNT: 1
      PROVIDED BY: /usr/lib/libgcc_s.so.1 (0x00007f897c503000)
      FAILED BECAUSE: Unsafe dependency
```
I did some googling and came to the conclusion that is was throwing this because the dep-selector-libgeocode was linking against a local version of these libraries (eg: ```/usr/lib/libstdc++.so.6```) rather than a version living under ```/opt/chefdk/embedded/lib/```. I just don't know where the change should be made to make sure it tries to link to an embedded library or whether this could be ignored, or what.

Ruby version
```
[uncurlhalo@tiger omnibus-chef]$ ruby -v
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux]
```
Built with the latests omnibus-chef version from git.

**Comment by hugosato** [comment]
Libraries libstdc++.so, libgcc_s, and libstdc++  aren't whitelisted in [ARCH](https://github.com/chef/omnibus/blob/ecf3cd4a7bd3870783176cdc11b2ba72007c124b/lib/omnibus/health_check.rb#L38) target platform. As result, dep-selector-libgeocode must be dependent on these (I suppose it is via  [gcc](https://github.com/chef/omnibus-software/blob/master/config/software/gcc.rb) omnibus-software)

However, I don't see any such usage in [omnibus-chef](https://github.com/chef/omnibus-chef/search?utf8=%E2%9C%93&q=gcc).

**Comment by yzl** [comment]
@hugosato The whitelists are in [omnibus](https://github.com/chef/omnibus/blob/master/lib/omnibus/health_check.rb) itself.

**Comment by hugosato** [comment]
Hi @yzl, if I understood @Uncurlhalo's log correctly, he is trying to build a project for Arch platform. After quick look [at the code](https://github.com/chef/omnibus/blob/0c3bbdf4742639897a8fa204b4e92083475e8b0b/lib/omnibus/health_check.rb#L409), it seemed to me the health check failures are by design.

I would suggest him to add these libraries as dependency. Also, fwict, he needs to create his own definition for ARCH since the [libgcc](https://github.com/chef/omnibus-software/blame/master/config/software/libgcc.rb#L42) won't be copied under the embedded folder for his platform.

or did I miss anything?

**Comment by yzl** [comment]
@hugosato That sounds about right, with the caveat that the existing ARCH whitelist predates ChefDK, so there might be cases where updating the whitelist would make more sense than managing a separate dependency.  (We don't build on ARCH, so I don't have specific knowledge to contribute on that front.)
