### ISSUE TITLE
Add testing and build support for Centos7 and Ubuntu 14.04

### ISSUE THREAD

**Issue by tyler-ball** [chef/omnibus-chef#339]
This will soon be Ubuntu 15.04 too

**Comment by schisamo** [comment]
@tyler-ball We already test/release on Ubuntu 14.04. I wonder if the download page code just needs some updating. You can grab the 0.4.0 from a number of locations:

* Apt repo: https://packagecloud.io/chef/stable/packages/ubuntu/trusty/chefdk_0.4.0-1_amd64.deb
* Omnitruck:
```
➜  curl "http://www.chef.io/chef/metadata-chefdk?p=ubuntu&pv=14.04&m=x86_64"
url	http://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/12.04/x86_64/chefdk_0.4.0-1_amd64.deb
md5	88db6add9590717ee3b34ffd468c0874
sha256	e135c0719fc80fc7b95560e90839103167308a45d4927cf8da9c22bdc385cc7d
```
* Artifactroy (Chef internal only): http://artifactory.chef.co/webapp/browserepo.html?6&pathId=omnibus-stable-local:com/getchef/chefdk/0.4.0/ubuntu/14.04/chefdk_0.4.0-1_amd64.deb

**Comment by tyler-ball** [comment]
@schisamo I filed this issue really fast - I obviously didn't do a good job filling in details because I don't remember exactly what I was talking about...

I just checked the [download page](https://www.chef.io/download-chef-client/) and it lists Ubuntu 14.04 correctly.  So it doesn't look like that needs updating.  But I think when I originally filed this issue, that was one of the things I was talking about.

I also think I remember the download page being generated from the packages available in artifactory, but now that 14.04 is in artifactory the download page lists it correctly.

The linked issue (https://github.com/chef/omnibus-chef/issues/195) is still open but I'm going to close this because the download page now lists 14.04 correctly.

**Comment by schisamo** [comment]
@tyler-ball https://downloads.chef.io/chef-dk/ubuntu/#/ now shows Ubuntu 14.04. We are working on getting the EL7 test infrastructure in place but it's lower priority ATM.

**Comment by tyler-ball** [comment]
:+1: I saw the download page!  If EL7 is already on your radar (and tracked elsewhere), feel free to close this

**Comment by pburkholder** [comment]
@schisamo How do we get EL7 built? I presume it's or involved than tweaking jenkins/chef.json and .kitchen.yml. I'm getting ask for it from customers. Thanks, Peter

**Comment by schisamo** [comment]
@pburkholder EL7 support for our full product suite is a Q2 project OCIV is working on
