### ISSUE TITLE
chefdk: fauxhai executable isn't in embedded/bin

### ISSUE THREAD

**Issue by docwhat** [chef/omnibus-chef#340]
I'm using the `ln -nfs /opt/chefdk/embedded $RBENV_ROOT/versions/chefdk` trick to get rbenv to use chefdk as a ruby on OS X.

However, the fauxhai binary isn't in the `/opt/chefdk/embedded/bin`, only in the `/opt/chefdk/bin` directory.

Is there even a reason to have the embedded hierarchy for ChefDK anymore?  It only contains the `bin/` directory and the `embedded/` directory.  The embedded stuff could all be moved up a directory and simplify things.  It should also make it play nicer with rbenv, rvm, and friends.

**Comment by docwhat** [comment]
I take back my comment about removing `/bin/` and moving everything up.  I feel that `embedded/bin` is currently evil... It overwrites system commands, like `clear`, `xz`, and `tput`.  Those should not be there.

In addition, all the gems ChefDK pre-installs, should be in the `/opt/chefdk/embedded/lib/ruby/gems/<version>/bin` directory and in the `/opt/chefdk/bin` directory.

I have to admit, I'm confused why there are two bin directories? Is it just to force certain commands to come before custom installed gems?  If so, then system-type commands should be moved into a third directory and only called with an absolute path in your code.

**Comment by lamont-granquist** [comment]
the "evil" is why embedded/bin is there and why there's two bins.  it was never intended to be put in the `$PATH`.  if we moved the ruby binaries itself that are currently in embedded into /opt/chefdk/bin would that solve most of these problems without creating another thing?  we could move them there, but not symlink those into /usr/bin.

**Comment by docwhat** [comment]
If it isn't intended to be in `$PATH` then why does `chef shell-init` add it at the 3rd item?

```
$ chef shell-init bash
export PATH="/opt/chefdk/bin:/Users/docwhat/.chefdk/gem/ruby/2.1.0/bin:/opt/chefdk/embedded/bin:/opt/chefdk/bin:..."
export GEM_ROOT="/opt/chefdk/embedded/lib/ruby/gems/2.1.0"
export GEM_HOME="/Users/docwhat/.chefdk/gem/ruby/2.1.0"
export GEM_PATH="/Users/docwhat/.chefdk/gem/ruby/2.1.0:/opt/chefdk/embedded/lib/ruby/gems/2.1.0"
```

**Comment by lamont-granquist** [comment]
because we forgot why we designed it that way?

**Comment by docwhat** [comment]
*LOL*

**Comment by docwhat** [comment]
@lamont-granquist -- Should I close this and create a better bug about the separation between `embedded/bin` and `bin`?  Either here or on chef/chef-dk?

**Comment by lamont-granquist** [comment]
I'm not sure.  This is definitely chef-dk specific and I don't think we'd pick it up for chef-client, so the bug should probably go in that repo.  It'd mean changes to chef exec and chef shell-init to stop adding the embedded path as well as packaging fixes.
