### ISSUE TITLE
chef_gem resource installs gems into push-jobs' environment instead of Chef client's

### ISSUE THREAD

**Issue by jeremiahsnapp** [chef/omnibus-chef#352]
@manderson26 

The installation of push-jobs appends the push-jobs's embedded environment to the system's `PATH` environment variable.

```
C:\Users\vagrant>echo %path%
C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\OpenSSH\bin;C:\opscode\chef\bin;C:\opscode\pushy\bin;C:\opscode\pushy\embedded\bin;C:\opscode\pushy\embedded\lib\zeromq\bin
```

This causes Chef's embedded ruby and gem environment to mistakenly use the push-jobs' ruby and gem environment.

```
C:\Users\vagrant>c:\opscode\chef\embedded\bin\gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 1.8.28
  - RUBY VERSION: 1.9.3 (2013-11-22 patchlevel 484) [i386-mingw32]
  - INSTALLATION DIRECTORY: C:/opscode/pushy/embedded/lib/ruby/gems/1.9.1
  - RUBY EXECUTABLE: C:/opscode/pushy/embedded/bin/ruby.exe
  - EXECUTABLE DIRECTORY: C:/opscode/pushy/embedded/bin
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86-mingw32
  - GEM PATHS:
     - C:/opscode/pushy/embedded/lib/ruby/gems/1.9.1
     - C:/Users/vagrant/.gem/ruby/1.9.1
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :benchmark => false
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - http://rubygems.org/
```

The workaround I've come up with is to remove the push-jobs embedded paths from the PATH environment variable during the chef-client run. This only affects the environment variable as the chef-client sees it. It does not make a permanent change to the environment variable.

The following line can be put in either a recipe or in the node's client.rb file. If you put it in a recipe you need to make sure it comes before any chef_gem resources are declared.

```
ENV['PATH'] = ENV['PATH'].split(";").delete_if { |p| p.match(/pushy\\embedded/) }.join(';')
```

**Comment by lamont-granquist** [comment]
wrong repo and most likely better solved by getting push client fully integrated with chef-client.
