### ISSUE TITLE
ENV["SSL_CERT_FILE"] = candidate_ca_bundle in ssl_env_hack.rb fails.

### ISSUE THREAD

**Issue by fog1985** [chef/omnibus-chef#365]
File as follow fails on setting ENV...:
https://github.com/chef/omnibus-chef/blob/master/files/openssl-customization/windows/ssl_env_hack.rb

C:/opscode/chef/embedded/lib/ruby/site_ruby/2.0.0/ssl_env_hack.rb:31:in `[]=': Invalid argument - ruby_setenv (Errno::EINVAL)

31st line is as follow:
ENV["SSL_CERT_FILE"] = candidate_ca_bundle

I have tried to put "PUTS candidate_ca_bundle" before that and it seems that everything is fine. But ENV variable can;t be set for some reason. 

Here what I have done and what is the result:

    if File.exist?(candidate_ca_bundle)
		puts "FILE EXISTS: #{candidate_ca_bundle}"
      ENV["SSL_CERT_FILE"] = candidate_ca_bundle

result:

PS C:\Users\tklym> chef-client
FILE EXISTS: C:/opscode/chef/embedded/ssl/certs/cacert.pem
C:/opscode/chef/embedded/lib/ruby/site_ruby/2.0.0/ssl_env_hack.rb:31:in `[]=': Invalid argument - ruby_setenv (Errno::EINVAL)

So file exists but it can't be assigned.

Operation System version: Windows Server 2008 R2 Enterprise SP1

**Comment by lamont-granquist** [comment]
needs to be reopened against chef/chef if this is still a bug
