### ISSUE TITLE
ChefDK current litters /tmp

### ISSUE THREAD

**Issue by BackSlasher** [chef/omnibus-chef#450]
I noticed this should be "fixed" in `master` because using a newer bundler version, so if this is N/A then apologies, and maybe it'll help for other people with this issue.
Currently, running `berks verify` on a cookbook with large complexity graph generates many `/tmp/d*-*-*` directories with githash-named files inside.
Bundle 1.7.12 provided with ChefDK has issue bundler/bundler#3366, which might be the cause IMO. Fixed in bundler 1.8.

**Comment by ksubrama** [comment]
Yes, we've been having issues with that version of bundler in other areas as well.  We should update the bundler we ship with chef-client and chef-dk.

**Comment by BackSlasher** [comment]
`master` points to another version if I'm not mistaken
