### ISSUE TITLE
Chef and ChefDK using different versions of Ruby on Windows (2.0.0 vs 2.1.6)

### ISSUE THREAD

**Issue by stuartpreston** [chef/omnibus-chef#465]
I have two Windows Servers, one with Chef Client 12.4.1 and one with ChefDK 0.7.0 (which bundles Chef Client 12.4.1).

The one with just the Chef Client is still using Ruby 2.0.0p451

![2015-08-22_22-02-43](https://cloud.githubusercontent.com/assets/6384654/9425872/537ffdf8-491a-11e5-871d-8bde235bc32f.png)

I'm guessing this has been discussed a bit before, but for consistency and security (ref #324), but shouldn't the ChefDK and Chef Client should use the same Ruby version? Otherwise there's no guarantee that code that executes on my workstation will execute the same way on the server.

**Comment by ksubrama** [comment]
ChefDK is considered to be more experimental and we expect developers to use it on their workstations - we don't expect it to land in production environments.  Currently, we have a couple of known issues and instabilities with Ruby >= 2.1 and some of the resources/cookbooks that are popular in chef when used on Windows.  Hence, we don't ship it with chef-client.  Ruby 2.1 on the other hand has a number of performance improvements - both on and off Windows.  We figure devs would appreciate that.  Once, we have stabilized and feel more confident about Ruby 2.1 on Windows, we'll sync them up and try to keep them synced in the future.

This is also why some of the other gems shipped with Chef-DK vs Chef Client (such as bundler) are at different versions.

**Comment by stuartpreston** [comment]
All fair comment, thanks. I haven't encountered significant issues with 2.1.6 as yet on Windows (especially as the ConEmu issues are fixed there) - hoping we can get confident about it soon.
