### ISSUE TITLE
Chef uninstallation restarts Windows 2012 network stack

### ISSUE THREAD

**Issue by rveznaver** [chef/omnibus-chef#536]
Hi,

We have Chef Client v12.4.1 installed on Windows 2012 and it seems the Chef uninstaller restarts the whole Windows 2012 network stack, causing the server to go offline for a minute or two until the service restart is complete. This happens both when uninstalling Chef Client v12.4.1 and when upgrading to Chef Client v12.5.1. 

When uninstalling with: ```wmic product where name="Chef Client v12.4.1" call uninstall``` the uninstaller will run silently and not restart the services, however it will set the windows pending reboot flag and will reboot once this flag is processed (therefore going offline for an even longer time).

When uninstalling through the GUI, the following message is displayed:
```
The following applications should be closed before continuing the install:

    DHCP Client
    Windows Event Log
    TCP/IP NetBIOS Helper
    Windows Connection Manager
    Application Information
    Background Intelligent Transfer Service
    Certificate Propagation
    Group Policy Client
    IKE and AuthIP IPsec Keying Modules
    IP Helper
    Server
    User Profile Service
    Task Scheduler
    System Event Notification Service
    Remote Desktop Configuration
    Shell Hardware Detection
    Themes
    Windows Management Instrumentation
    Windows Update
    COM+ Event System
    Windows Font Cache Service
    Network List Service
    Network Store Interface Service
    Windows Time
    WinHTTP Web Proxy Auto-Discovery Service
    Cryptographic Serbices
    DNS Client
    Workstation
    Network Location Awareness
    Windows Remote Management (WS-Management)
    nxlog
```

The default action when running ```msiexec /qn /i "chef-client-12.5.1-1.windows.msi" ADDLOCAL="ChefClientFeature"``` will do the service restart and then upgrade the Chef Client, however it is painful to automate as the server goes offline for a while (so it has to be orchestrated).

Could you please reproduce and confirm?

**Comment by btm** [comment]
Is the Chef Client service running when you upgrade/uninstall?

**Comment by rveznaver** [comment]
Nope. Also, we don't run Chef on Windows as a service, but a Scheduled Task.

I have also noticed that if I reboot the machine beforehand it will perform the uninstall/upgrade thing cleanly. However, it will set up reboot flags, therefore rebooting on the next Chef run (as we use the reboot handler from the windows cookbook).

**Comment by btm** [comment]
Are you using Chef to run the uninstall or upgrade?

Do you think any Chef processes are running (e.g. task executing) when you uninstall or upgrade?

I've uninstalled / reinstalled the 12.4.1 msi a few times with and without the service fine on 2012 so far. I did see a warning about a reboot when I installed 12.5.1 with the service, started it, then went to uninstall. If I didn't start the service I didn't get the warning.

**Comment by rveznaver** [comment]
We're connecting to machines using RunDeck + WinRM, but I have the same issue when connecting through rdesktop and running it via cmd.

No Chef processes are running. We disable the task and end it before the install.

I have also tried to reproduce it in a VM, however without any luck so far. On the other side, absolutely every single one of our Windows 2012 server pool appears to have this issue.

**Comment by btm** [comment]
If I log on a VM and run chef-shell, then try to uninstall, I says I need to close ruby. Same thing if I run chef-shell over winrm. I can't reproduce a popup with a list of services anymore...

So what's interesting about your list of processes is "Windows Remote Management (WS-Management)" and "nxlog"

What are you doing with nxlog? Any chance it has a winrm connection and it's hooked into a chef-client log or something? What happens if you make that go away before you try to uninstall?

**Comment by btm** [comment]
@rveznaver have you made any progress on this?

**Comment by rveznaver** [comment]
Hi @btm, sorry to keep you waiting, but will most definitely continue working on this as soon as I get back from the Chef Summit in London.

**Comment by rveznaver** [comment]
Hi @btm,

This seems to be an issue on our side. We configure nxlog to forward the Chef client.log, and nxlog (running as a service) keeps a lock on that file (found it with Process Explorer). Stopping the nxlog service releases the lock and Chef upgrades without any problems. I still have no idea why the Windows Restart Manager thought it should restart all those other services as well, so there might be a small bug hiding in there, but that doesn't matter any more as it is not triggered when nxlog is stopped.

Thank you so much for your help! If we ever meet at a summit/conference you have a :beer: on me :)
