### ISSUE TITLE
Missing tag `chef-12.6.0`

### ISSUE THREAD

**Issue by rhass** [chef/omnibus-chef#574]
It seems the `12.6.0` chef client tag is missing.

**Comment by coderanger** [comment]
ChefDK 0.10 is also missing.

**Comment by coderanger** [comment]
Given the repo reshuffle, it seems unlikely this will ever be fixed. /cc @chef/client-core

**Comment by danielsdeleo** [comment]
Github tags list says there is a chef-12.6.0 tag (https://github.com/chef/omnibus-chef/tree/chef-12.6.0), but not one for chefdk-0.10.0

**Comment by lamont-granquist** [comment]
yep
