### ISSUE TITLE
chefdk package includes multiple versions of gems

### ISSUE THREAD

**Issue by jklare** [chef/omnibus-chef#577]
Hi,

i recently discovered, that the chefdk package includes some gems like "activesupport" that seem to originate from some dependencies during the build process, but are not directly mentioned in the dependencies of the chefdk project itself (not included in the Gemfile.lock after bundle install for chefdk). @coderanger was very helpful with the details and pointed me to this file https://github.com/chef/omnibus-chef/blob/master/config/software/chefdk.rb#L24-L54 , where the dependencies are written down. In addition to this, there are also two versions of activesupport installed which seems strange to me. Since multiple versions of gems (e.g. currently 3 versions of rake or the mentioned 2 versions of activesupport) can lead to a lot of issues and are usually not necessary, i would love to solve this and only include one gem version per package if possible. Also it would be great to generate something like a Gemfile.lock during this build process to figure out the dependencies more easily.

Cheers,
Jan

**Comment by coderanger** [comment]
So as I explained on IRC, this is not a bug. Different software configs in omnibus pull in different versions and we use appbundler to isolate them when needed.
